### ISSUE TITLE
Feature request: `cd` into workspace directory after launching VSCode

### ISSUE THREAD

**Issue by israelroldan** [woudsma/workspaces-cli#1]
Hi!

I'm a happy user of this package and I would love if it changed my working directory to the directory of the workspace so that I can continue working in that terminal in that workspace's context!

Great work!

**Comment by woudsma** [comment]
When selecting a workspace, you enter a subshell in the workspace directory.
I'm open to suggestions on how to show the shell cursor from the child process!
New version deployed with https://github.com/woudsma/workspaces-cli/commit/baf7afef20654306c06577bee9891e8897163b1e 🎉
```
npm update -g @woudsma/workspaces-cli
```
